# -*- coding: utf-8 -*-
"""kbc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TA0-O3CkKggkdGDfREGCAyxwcDF6iXZY
"""

question = [["1. How many continents are there"],
            ["2. what is the capital of India"], 
            ["3. Which course is taught in NG"]]

option_list=[["1.Four","2.Nine","3.Seven","4.Eight"],
             ["1.Chandigarh","2.Bhopal","3.Chennai","4.Delhi"],
             ["1.SE","2.Tourism","3.Counselling","4.agriculure"]]

answers=[3,4,1]

fifty=[["2.Nine","3.Seven"],["1.Chandigarh","4.Delhi"],["1.SE","2.Tourism"]]

count=0
print("Apka sawal hai")

i=0
while i<len(question):
  print("\n",question[i])
  j=0
  while j<len(option_list[i]):
    print("\n",option_list[i][j])
    j+=1
  input2=input("do you want a lifeline?")
  if input2=="yes":
        count+=1
        if count==1:
          print(fifty[i])
        else:
          print("You have already used a lifeline")
          pass   
  else:
    print("Choose the correct option")
  input1=int(input("enter your number option: "))
  
  if input1==answers[i]:
    print("great!")
  else:
    print("sorry thats not correct answer ")
    break
  
  i+=1



























